# Generated by Django 2.1.1 on 2018-10-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=7)),
                ('garage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Garage')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Cars')),
            ],
        ),
    ]
